### ISSUE TITLE
Minor error in bash variable calling?

### ISSUE THREAD

**Issue by FranckLejzerowicz** [laxeye/YAMB#2]
Hello there!
I had this issue while trying your tool:
```
Argument "LENGTH" isn't numeric in integer multiplication (*) at cut-contigs.pl line 47.
```

I think this can be fixed easily, there: https://github.com/laxeye/YAMB/blob/5dab69c28473152063ad012d48b5492814184f53/yamb.sh#L89
by changing `LENGTH` to `$LENGTH`

Hope that helps

**Comment by laxeye** [comment]
Dear Franck @FranckLejzerowicz, thank you for paying attention to the tool! I'll fix this issue.
